// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tylancgjmllwhuzptlxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5bGFuY2dqbWxsd2h1enB0bHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNDk3NzQsImV4cCI6MjA2NjgyNTc3NH0.OiTSntTf3dqWLIONinCIz6X6NJaior0qEasTuOw-2_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});